CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AccountingEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntryDate" timestamp with time zone NOT NULL,
    "Description" character varying(300) NOT NULL,
    "Source" character varying(50) NOT NULL,
    "SourceReference" character varying(100) NOT NULL,
    CONSTRAINT "PK_AccountingEntries" PRIMARY KEY ("Id")
);

CREATE TABLE "Agencies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "TaxId" character varying(50),
    "Email" character varying(200),
    "Phone" character varying(50),
    "Address" character varying(300),
    "CreditLimit" numeric(12,2) NOT NULL,
    "CurrentBalance" numeric(12,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Agencies" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "BspImportBatches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" character varying(200) NOT NULL,
    "Format" character varying(20) NOT NULL,
    "ImportedAt" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "ClosedAt" timestamp with time zone,
    CONSTRAINT "PK_BspImportBatches" PRIMARY KEY ("Id")
);

CREATE TABLE "Cupos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "ProductType" character varying(50) NOT NULL,
    "TravelDate" timestamp with time zone NOT NULL,
    "Capacity" integer NOT NULL,
    "OverbookingLimit" integer NOT NULL,
    "Reserved" integer NOT NULL,
    "RowVersion" uuid NOT NULL,
    CONSTRAINT "PK_Cupos" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(200) NOT NULL,
    "Email" character varying(200),
    "Phone" text,
    "DocumentNumber" character varying(50),
    "Address" character varying(300),
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "TaxId" character varying(20),
    "CreditLimit" numeric NOT NULL,
    "CurrentBalance" numeric NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "Suppliers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "ContactName" character varying(100),
    "Email" character varying(200),
    "Phone" character varying(50),
    "TaxId" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CurrentBalance" numeric NOT NULL,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
);

CREATE TABLE "Tariffs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500),
    "ProductType" character varying(50) NOT NULL,
    "Currency" character varying(10),
    "DefaultPrice" numeric(12,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tariffs" PRIMARY KEY ("Id")
);

CREATE TABLE "TreasuryReceipts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Reference" character varying(100) NOT NULL,
    "Method" character varying(50) NOT NULL,
    "Currency" character varying(10),
    "Amount" numeric(12,2) NOT NULL,
    "ReceivedAt" timestamp with time zone NOT NULL,
    "Notes" character varying(500),
    CONSTRAINT "PK_TreasuryReceipts" PRIMARY KEY ("Id")
);

CREATE TABLE "AccountingLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountCode" character varying(20) NOT NULL,
    "Debit" numeric(12,2) NOT NULL,
    "Credit" numeric(12,2) NOT NULL,
    "Currency" character varying(10) NOT NULL,
    "AccountingEntryId" integer NOT NULL,
    CONSTRAINT "PK_AccountingLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountingLines_AccountingEntries_AccountingEntryId" FOREIGN KEY ("AccountingEntryId") REFERENCES "AccountingEntries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "AgencyId" integer,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Agencies_AgencyId" FOREIGN KEY ("AgencyId") REFERENCES "Agencies" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BspImportRawRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LineNumber" integer NOT NULL,
    "RawContent" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "BspImportBatchId" integer NOT NULL,
    CONSTRAINT "PK_BspImportRawRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BspImportRawRecords_BspImportBatches_BspImportBatchId" FOREIGN KEY ("BspImportBatchId") REFERENCES "BspImportBatches" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BspNormalizedRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TicketNumber" character varying(50) NOT NULL,
    "ReservationReference" character varying(50) NOT NULL,
    "IssueDate" timestamp with time zone NOT NULL,
    "Currency" character varying(10) NOT NULL,
    "BaseAmount" numeric(12,2) NOT NULL,
    "TaxAmount" numeric(12,2) NOT NULL,
    "TotalAmount" numeric(12,2) NOT NULL,
    "BspImportBatchId" integer NOT NULL,
    CONSTRAINT "PK_BspNormalizedRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BspNormalizedRecords_BspImportBatches_BspImportBatchId" FOREIGN KEY ("BspImportBatchId") REFERENCES "BspImportBatches" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Quotes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReferenceCode" character varying(50) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CustomerId" integer NOT NULL,
    CONSTRAINT "PK_Quotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Quotes_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Reservas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileNumber" character varying(50) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ClosedAt" timestamp with time zone,
    "PayerId" integer,
    CONSTRAINT "PK_TravelFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TravelFiles_Customers_PayerId" FOREIGN KEY ("PayerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TariffValidities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Price" numeric(12,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "TariffId" integer NOT NULL,
    CONSTRAINT "PK_TariffValidities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TariffValidities_Tariffs_TariffId" FOREIGN KEY ("TariffId") REFERENCES "Tariffs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "QuoteVersions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VersionNumber" integer NOT NULL,
    "ProductType" character varying(50) NOT NULL,
    "Currency" character varying(10),
    "TotalAmount" numeric(12,2) NOT NULL,
    "ValidUntil" timestamp with time zone,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "QuoteId" integer NOT NULL,
    CONSTRAINT "PK_QuoteVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_QuoteVersions_Quotes_QuoteId" FOREIGN KEY ("QuoteId") REFERENCES "Quotes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Servicios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReferenceCode" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ProductType" character varying(50) NOT NULL,
    "DepartureDate" timestamp with time zone NOT NULL,
    "ReturnDate" timestamp with time zone,
    "BasePrice" numeric(12,2) NOT NULL,
    "Commission" numeric(12,2) NOT NULL,
    "TotalAmount" numeric(12,2) NOT NULL,
    "SupplierName" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CustomerId" integer NOT NULL,
    "TravelFileId" integer,
    CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reservations_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reservations_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "BspReconciliationEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Status" character varying(30) NOT NULL,
    "DifferenceAmount" numeric(12,2),
    "ReconciledAt" timestamp with time zone NOT NULL,
    "BspImportBatchId" integer NOT NULL,
    "BspNormalizedRecordId" integer NOT NULL,
    "ReservationId" integer,
    CONSTRAINT "PK_BspReconciliationEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BspReconciliationEntries_BspImportBatches_BspImportBatchId" FOREIGN KEY ("BspImportBatchId") REFERENCES "BspImportBatches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BspReconciliationEntries_BspNormalizedRecords_BspNormalized~" FOREIGN KEY ("BspNormalizedRecordId") REFERENCES "BspNormalizedRecords" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BspReconciliationEntries_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE SET NULL
);

CREATE TABLE "CupoAssignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CupoId" integer NOT NULL,
    "ReservationId" integer,
    "Quantity" integer NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CupoAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CupoAssignments_Cupos_CupoId" FOREIGN KEY ("CupoId") REFERENCES "Cupos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CupoAssignments_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE SET NULL
);

CREATE TABLE "FlightSegments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AirlineCode" character varying(3) NOT NULL,
    "FlightNumber" character varying(10) NOT NULL,
    "Origin" character varying(3) NOT NULL,
    "Destination" character varying(3) NOT NULL,
    "DepartureTime" timestamp with time zone NOT NULL,
    "ArrivalTime" timestamp with time zone NOT NULL,
    "Status" character varying(2) NOT NULL,
    "ReservationId" integer NOT NULL,
    CONSTRAINT "PK_FlightSegments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FlightSegments_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Amount" numeric(12,2) NOT NULL,
    "PaidAt" timestamp with time zone NOT NULL,
    "Method" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ReservationId" integer NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TreasuryApplications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AmountApplied" numeric(12,2) NOT NULL,
    "AppliedAt" timestamp with time zone NOT NULL,
    "TreasuryReceiptId" integer NOT NULL,
    "ReservationId" integer NOT NULL,
    CONSTRAINT "PK_TreasuryApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TreasuryApplications_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TreasuryApplications_TreasuryReceipts_TreasuryReceiptId" FOREIGN KEY ("TreasuryReceiptId") REFERENCES "TreasuryReceipts" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AccountingLines_AccountingEntryId" ON "AccountingLines" ("AccountingEntryId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_AgencyId" ON "AspNetUsers" ("AgencyId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_BspImportRawRecords_BspImportBatchId" ON "BspImportRawRecords" ("BspImportBatchId");

CREATE INDEX "IX_BspNormalizedRecords_BspImportBatchId" ON "BspNormalizedRecords" ("BspImportBatchId");

CREATE INDEX "IX_BspReconciliationEntries_BspImportBatchId" ON "BspReconciliationEntries" ("BspImportBatchId");

CREATE UNIQUE INDEX "IX_BspReconciliationEntries_BspNormalizedRecordId" ON "BspReconciliationEntries" ("BspNormalizedRecordId");

CREATE INDEX "IX_BspReconciliationEntries_ReservationId" ON "BspReconciliationEntries" ("ReservationId");

CREATE INDEX "IX_CupoAssignments_CupoId" ON "CupoAssignments" ("CupoId");

CREATE INDEX "IX_CupoAssignments_ReservationId" ON "CupoAssignments" ("ReservationId");

CREATE INDEX "IX_FlightSegments_ReservationId" ON "FlightSegments" ("ReservationId");

CREATE INDEX "IX_Payments_ReservationId" ON "Payments" ("ReservationId");

CREATE INDEX "IX_Quotes_CustomerId" ON "Quotes" ("CustomerId");

CREATE INDEX "IX_QuoteVersions_QuoteId" ON "QuoteVersions" ("QuoteId");

CREATE INDEX "IX_Reservations_CustomerId" ON "Servicios" ("CustomerId");

CREATE INDEX "IX_Reservations_TravelFileId" ON "Servicios" ("TravelFileId");

CREATE INDEX "IX_TariffValidities_TariffId" ON "TariffValidities" ("TariffId");

CREATE INDEX "IX_TravelFiles_PayerId" ON "Reservas" ("PayerId");

CREATE INDEX "IX_TreasuryApplications_ReservationId" ON "TreasuryApplications" ("ReservationId");

CREATE INDEX "IX_TreasuryApplications_TreasuryReceiptId" ON "TreasuryApplications" ("TreasuryReceiptId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260119202735_InitialRetailPivot', '8.0.13');

COMMIT;

START TRANSACTION;

CREATE TABLE "CommissionRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SupplierId" integer,
    "ServiceType" character varying(50),
    "CommissionPercent" numeric(5,2) NOT NULL,
    "Priority" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Description" character varying(200),
    CONSTRAINT "PK_CommissionRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CommissionRules_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id")
);

CREATE INDEX "IX_CommissionRules_SupplierId" ON "CommissionRules" ("SupplierId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260206033001_AddCommissionRules', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "FlightSegments" ALTER COLUMN "ReservationId" DROP NOT NULL;

ALTER TABLE "FlightSegments" ADD "AirlineName" character varying(100);

ALTER TABLE "FlightSegments" ADD "Baggage" character varying(50);

ALTER TABLE "FlightSegments" ADD "CabinClass" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "FlightSegments" ADD "Commission" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "FlightSegments" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "FlightSegments" ADD "DestinationCity" character varying(100);

ALTER TABLE "FlightSegments" ADD "FareBase" character varying(20);

ALTER TABLE "FlightSegments" ADD "NetCost" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "FlightSegments" ADD "Notes" character varying(500);

ALTER TABLE "FlightSegments" ADD "OriginCity" character varying(100);

ALTER TABLE "FlightSegments" ADD "PNR" character varying(20);

ALTER TABLE "FlightSegments" ADD "SalePrice" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "FlightSegments" ADD "SupplierId" integer NOT NULL DEFAULT 0;

ALTER TABLE "FlightSegments" ADD "Tax" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "FlightSegments" ADD "TicketNumber" character varying(50);

ALTER TABLE "FlightSegments" ADD "TravelFileId" integer NOT NULL DEFAULT 0;

CREATE TABLE "HotelBookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TravelFileId" integer NOT NULL,
    "SupplierId" integer NOT NULL,
    "HotelName" character varying(200) NOT NULL,
    "StarRating" integer,
    "Address" character varying(200),
    "City" character varying(100) NOT NULL,
    "Country" character varying(100),
    "CheckIn" timestamp with time zone NOT NULL,
    "CheckOut" timestamp with time zone NOT NULL,
    "Nights" integer NOT NULL,
    "RoomType" character varying(50) NOT NULL,
    "MealPlan" character varying(50) NOT NULL,
    "Rooms" integer NOT NULL,
    "Adults" integer NOT NULL,
    "Children" integer NOT NULL,
    "ConfirmationNumber" character varying(100),
    "Status" character varying(50) NOT NULL,
    "NetCost" numeric(18,2) NOT NULL,
    "SalePrice" numeric(18,2) NOT NULL,
    "Commission" numeric(18,2) NOT NULL,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HotelBookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HotelBookings_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_HotelBookings_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PackageBookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TravelFileId" integer NOT NULL,
    "SupplierId" integer NOT NULL,
    "PackageName" character varying(200) NOT NULL,
    "Destination" character varying(100) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Nights" integer NOT NULL,
    "IncludesHotel" boolean NOT NULL,
    "IncludesFlight" boolean NOT NULL,
    "IncludesTransfer" boolean NOT NULL,
    "IncludesExcursions" boolean NOT NULL,
    "IncludesMeals" boolean NOT NULL,
    "Adults" integer NOT NULL,
    "Children" integer NOT NULL,
    "Itinerary" character varying(2000),
    "ConfirmationNumber" character varying(100),
    "Status" character varying(50) NOT NULL,
    "NetCost" numeric(18,2) NOT NULL,
    "SalePrice" numeric(18,2) NOT NULL,
    "Commission" numeric(18,2) NOT NULL,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PackageBookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PackageBookings_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PackageBookings_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Rates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SupplierId" integer NOT NULL,
    "ServiceType" character varying(50) NOT NULL,
    "ProductName" character varying(200) NOT NULL,
    "Description" character varying(500),
    "NetCost" numeric(18,2) NOT NULL,
    "SalePrice" numeric(18,2) NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "ValidFrom" timestamp with time zone NOT NULL,
    "ValidTo" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Rates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rates_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TransferBookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TravelFileId" integer NOT NULL,
    "SupplierId" integer NOT NULL,
    "PickupLocation" character varying(200) NOT NULL,
    "DropoffLocation" character varying(200) NOT NULL,
    "PickupDateTime" timestamp with time zone NOT NULL,
    "FlightNumber" character varying(20),
    "VehicleType" character varying(50) NOT NULL,
    "Passengers" integer NOT NULL,
    "IsRoundTrip" boolean NOT NULL,
    "ReturnDateTime" timestamp with time zone,
    "ConfirmationNumber" character varying(100),
    "Status" character varying(50) NOT NULL,
    "NetCost" numeric(18,2) NOT NULL,
    "SalePrice" numeric(18,2) NOT NULL,
    "Commission" numeric(18,2) NOT NULL,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TransferBookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TransferBookings_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TransferBookings_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_FlightSegments_SupplierId" ON "FlightSegments" ("SupplierId");

CREATE INDEX "IX_FlightSegments_TravelFileId" ON "FlightSegments" ("TravelFileId");

CREATE INDEX "IX_HotelBookings_SupplierId" ON "HotelBookings" ("SupplierId");

CREATE INDEX "IX_HotelBookings_TravelFileId" ON "HotelBookings" ("TravelFileId");

CREATE INDEX "IX_PackageBookings_SupplierId" ON "PackageBookings" ("SupplierId");

CREATE INDEX "IX_PackageBookings_TravelFileId" ON "PackageBookings" ("TravelFileId");

CREATE INDEX "IX_Rates_SupplierId" ON "Rates" ("SupplierId");

CREATE INDEX "IX_TransferBookings_SupplierId" ON "TransferBookings" ("SupplierId");

CREATE INDEX "IX_TransferBookings_TravelFileId" ON "TransferBookings" ("TravelFileId");

ALTER TABLE "FlightSegments" ADD CONSTRAINT "FK_FlightSegments_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE;

ALTER TABLE "FlightSegments" ADD CONSTRAINT "FK_FlightSegments_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260206041325_AddServiceModels', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rates" DROP CONSTRAINT "FK_Rates_Suppliers_SupplierId";

ALTER TABLE "Rates" ALTER COLUMN "ValidTo" DROP NOT NULL;

ALTER TABLE "Rates" ALTER COLUMN "ValidFrom" DROP NOT NULL;

ALTER TABLE "Rates" ALTER COLUMN "SupplierId" DROP NOT NULL;

ALTER TABLE "Rates" ALTER COLUMN "Description" TYPE character varying(1000);

ALTER TABLE "Rates" ADD "Airline" character varying(100);

ALTER TABLE "Rates" ADD "AirlineCode" character varying(10);

ALTER TABLE "Rates" ADD "BaggageIncluded" character varying(100);

ALTER TABLE "Rates" ADD "CabinClass" character varying(50);

ALTER TABLE "Rates" ADD "City" character varying(100);

ALTER TABLE "Rates" ADD "Commission" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "Rates" ADD "Destination" character varying(100);

ALTER TABLE "Rates" ADD "DropoffLocation" character varying(100);

ALTER TABLE "Rates" ADD "DurationDays" integer;

ALTER TABLE "Rates" ADD "HotelName" character varying(150);

ALTER TABLE "Rates" ADD "IncludesExcursions" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Rates" ADD "IncludesFlight" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Rates" ADD "IncludesHotel" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Rates" ADD "IncludesInsurance" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Rates" ADD "IncludesTransfer" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Rates" ADD "InternalNotes" character varying(500);

ALTER TABLE "Rates" ADD "IsRoundTrip" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Rates" ADD "Itinerary" character varying(2000);

ALTER TABLE "Rates" ADD "MaxPassengers" integer;

ALTER TABLE "Rates" ADD "MealPlan" character varying(50);

ALTER TABLE "Rates" ADD "Origin" character varying(100);

ALTER TABLE "Rates" ADD "PickupLocation" character varying(100);

ALTER TABLE "Rates" ADD "PriceUnit" character varying(50) NOT NULL DEFAULT '';

ALTER TABLE "Rates" ADD "RoomType" character varying(100);

ALTER TABLE "Rates" ADD "StarRating" integer;

ALTER TABLE "Rates" ADD "Tax" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "Rates" ADD "VehicleType" character varying(50);

ALTER TABLE "Rates" ADD CONSTRAINT "FK_Rates_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260206151211_ProfessionalRateFields', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rates" ADD "ChildMaxAge" integer NOT NULL DEFAULT 0;

ALTER TABLE "Rates" ADD "ChildrenPayPercent" integer NOT NULL DEFAULT 0;

ALTER TABLE "Rates" ADD "HotelPriceType" character varying(20);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260206154319_HotelPricingFields', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rates" ADD "RoomCategory" character varying(100);

ALTER TABLE "Rates" ADD "RoomFeatures" character varying(200);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260206160123_HotelRoomDetails', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Reservas" ADD "CustomerId" integer;

ALTER TABLE "Servicios" ALTER COLUMN "ProductType" DROP NOT NULL;

ALTER TABLE "Customers" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

CREATE INDEX "IX_TravelFiles_CustomerId" ON "Reservas" ("CustomerId");

ALTER TABLE "Reservas" ADD CONSTRAINT "FK_TravelFiles_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209045652_AddIsActiveToCustomer', '8.0.13');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209135452_AddIsActiveToSupplier', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Reservas" DROP CONSTRAINT "FK_TravelFiles_Customers_CustomerId";

DROP INDEX "IX_TravelFiles_CustomerId";

ALTER TABLE "Reservas" DROP COLUMN "CustomerId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209192115_FixCustomerTravelFilesMapping', '8.0.13');

COMMIT;

START TRANSACTION;

CREATE TABLE "AfipSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cuit" bigint NOT NULL,
    "PuntoDeVenta" integer NOT NULL,
    "IsProduction" boolean NOT NULL,
    "CertificatePath" text,
    "CertificatePassword" text,
    "Token" text,
    "Sign" text,
    "TokenExpiration" timestamp with time zone,
    CONSTRAINT "PK_AfipSettings" PRIMARY KEY ("Id")
);

CREATE TABLE "Invoices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "TipoComprobante" integer NOT NULL,
    "PuntoDeVenta" integer NOT NULL,
    "NumeroComprobante" bigint NOT NULL,
    "CAE" text,
    "VencimientoCAE" timestamp with time zone,
    "Resultado" text,
    "Observaciones" text,
    "ImporteTotal" numeric(18,2) NOT NULL,
    "ImporteNeto" numeric(18,2) NOT NULL,
    "ImporteIva" numeric(18,2) NOT NULL,
    "TravelFileId" integer,
    CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Invoices_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id")
);

CREATE INDEX "IX_Invoices_TravelFileId" ON "Invoices" ("TravelFileId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209200608_AddAfipModule', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "AfipSettings" ADD "CertificateData" bytea;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209202029_AddCertificateDataToAfipSettings', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "AfipSettings" ADD "TaxCondition" character varying(50) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209205234_AddTaxConditionToAfipSettings', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Customers" ADD "TaxCondition" character varying(50) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209205640_AddTaxConditionToCustomer', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Customers" ADD "TaxConditionId" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260210212635_AddTaxConditionIdToCustomer', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "AgencySettings" ADD "ActivityStartDate" timestamp with time zone;

ALTER TABLE "AgencySettings" ADD "LegalName" character varying(200);

ALTER TABLE "AgencySettings" ADD "TaxCondition" character varying(50);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260210214824_AddInvoiceDetailsToAgencySettings', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Invoices" ADD "AgencySnapshot" text;

ALTER TABLE "Invoices" ADD "CustomerSnapshot" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260211014657_AddInvoiceSnapshots', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Payments" ADD "Reference" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260212040834_AddReferenceToPayment', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Payments" ADD "DeletedAt" timestamp with time zone;

ALTER TABLE "Payments" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215202704_AddSoftDeleteToPayments', '8.0.13');

COMMIT;

START TRANSACTION;

CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "UserName" text,
    "Action" character varying(50) NOT NULL,
    "EntityName" character varying(100) NOT NULL,
    "EntityId" character varying(100) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Changes" text,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260215210804_AddAuditLogs', '8.0.13');

COMMIT;

START TRANSACTION;

CREATE TABLE "TravelFileAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TravelFileId" integer NOT NULL,
    "FileName" text NOT NULL,
    "StoredFileName" text NOT NULL,
    "ContentType" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "UploadedBy" text NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TravelFileAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TravelFileAttachments_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TravelFileAttachments_TravelFileId" ON "TravelFileAttachments" ("TravelFileId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216191956_AddAttachmentsTable', '8.0.13');

COMMIT;

START TRANSACTION;


                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Invoices' AND column_name = 'OriginalInvoiceId') THEN
                        ALTER TABLE "Invoices" ADD "OriginalInvoiceId" integer;
                    END IF;
                END $$;
            


                CREATE TABLE IF NOT EXISTS "InvoiceItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "InvoiceId" integer NOT NULL,
                    "Description" character varying(200) NOT NULL,
                    "Quantity" numeric(18,2) NOT NULL,
                    "UnitPrice" numeric(18,2) NOT NULL,
                    "Total" numeric(18,2) NOT NULL,
                    "AlicuotaIvaId" integer NOT NULL,
                    "ImporteIva" numeric(18,2) NOT NULL,
                    CONSTRAINT "PK_InvoiceItems" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_InvoiceItems_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
                );
            


                CREATE TABLE IF NOT EXISTS "InvoiceTributes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "InvoiceId" integer NOT NULL,
                    "TributeId" integer NOT NULL,
                    "Description" character varying(200) NOT NULL,
                    "BaseImponible" numeric(18,2) NOT NULL,
                    "Alicuota" numeric(18,2) NOT NULL,
                    "Importe" numeric(18,2) NOT NULL,
                    CONSTRAINT "PK_InvoiceTributes" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_InvoiceTributes_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
                );
            

CREATE INDEX IF NOT EXISTS "IX_Invoices_OriginalInvoiceId" ON "Invoices" ("OriginalInvoiceId");

CREATE INDEX IF NOT EXISTS "IX_InvoiceItems_InvoiceId" ON "InvoiceItems" ("InvoiceId");

CREATE INDEX IF NOT EXISTS "IX_InvoiceTributes_InvoiceId" ON "InvoiceTributes" ("InvoiceId");


                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_Invoices_Invoices_OriginalInvoiceId') THEN
                        ALTER TABLE "Invoices" ADD CONSTRAINT "FK_Invoices_Invoices_OriginalInvoiceId" FOREIGN KEY ("OriginalInvoiceId") REFERENCES "Invoices" ("Id");
                    END IF;
                END $$;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216195937_AddAccountingEntities', '8.0.13');

COMMIT;

START TRANSACTION;

DROP TABLE IF EXISTS "LeadActivities" CASCADE;

DROP TABLE IF EXISTS "QuoteItems" CASCADE;

DROP TABLE IF EXISTS "Leads" CASCADE;

DROP TABLE IF EXISTS "Quotes" CASCADE;


                CREATE TABLE "Leads" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FullName" character varying(200) NOT NULL,
                    "Email" character varying(200),
                    "Phone" character varying(50),
                    "Status" character varying(50) NOT NULL,
                    "Source" character varying(50),
                    "InterestedIn" character varying(200),
                    "EstimatedBudget" numeric(18,2) NOT NULL DEFAULT 0,
                    "Notes" character varying(2000),
                    "AssignedToUserId" text,
                    "AssignedToName" character varying(200),
                    "NextFollowUp" timestamp with time zone,
                    "ConvertedCustomerId" integer,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "ClosedAt" timestamp with time zone,
                    CONSTRAINT "PK_Leads" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Leads_Customers_ConvertedCustomerId" FOREIGN KEY ("ConvertedCustomerId") REFERENCES "Customers" ("Id")
                );
            


                CREATE TABLE "Quotes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "QuoteNumber" character varying(50) NOT NULL,
                    "Title" character varying(200) NOT NULL,
                    "Description" character varying(2000),
                    "Status" character varying(50) NOT NULL,
                    "CustomerId" integer,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "ValidUntil" timestamp with time zone,
                    "AcceptedAt" timestamp with time zone,
                    "TravelStartDate" timestamp with time zone,
                    "TravelEndDate" timestamp with time zone,
                    "Destination" character varying(200),
                    "Adults" integer NOT NULL DEFAULT 2,
                    "Children" integer NOT NULL DEFAULT 0,
                    "TotalCost" numeric(18,2) NOT NULL DEFAULT 0,
                    "TotalSale" numeric(18,2) NOT NULL DEFAULT 0,
                    "GrossMargin" numeric(18,2) NOT NULL DEFAULT 0,
                    "ConvertedFileId" integer,
                    "Notes" character varying(500),
                    CONSTRAINT "PK_Quotes" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Quotes_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
                    CONSTRAINT "FK_Quotes_TravelFiles_ConvertedFileId" FOREIGN KEY ("ConvertedFileId") REFERENCES "Reservas" ("Id")
                );
            


                CREATE TABLE "LeadActivities" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LeadId" integer NOT NULL,
                    "Type" character varying(50) NOT NULL,
                    "Description" character varying(1000) NOT NULL,
                    "CreatedBy" character varying(200),
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_LeadActivities" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_LeadActivities_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE
                );
            


                CREATE TABLE "QuoteItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "QuoteId" integer NOT NULL,
                    "ServiceType" character varying(50) NOT NULL,
                    "Description" character varying(200) NOT NULL,
                    "SupplierId" integer,
                    "Quantity" integer NOT NULL DEFAULT 1,
                    "UnitCost" numeric(18,2) NOT NULL DEFAULT 0,
                    "UnitPrice" numeric(18,2) NOT NULL DEFAULT 0,
                    "MarkupPercent" numeric(18,2) NOT NULL DEFAULT 0,
                    "Notes" character varying(500),
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_QuoteItems" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_QuoteItems_Quotes_QuoteId" FOREIGN KEY ("QuoteId") REFERENCES "Quotes" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_QuoteItems_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id")
                );
            

CREATE INDEX "IX_LeadActivities_LeadId" ON "LeadActivities" ("LeadId");

CREATE INDEX "IX_Leads_ConvertedCustomerId" ON "Leads" ("ConvertedCustomerId");

CREATE INDEX "IX_QuoteItems_QuoteId" ON "QuoteItems" ("QuoteId");

CREATE INDEX "IX_QuoteItems_SupplierId" ON "QuoteItems" ("SupplierId");

CREATE INDEX "IX_Quotes_ConvertedFileId" ON "Quotes" ("ConvertedFileId");

CREATE INDEX "IX_Quotes_CustomerId" ON "Quotes" ("CustomerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260307124438_AddQuotesAndCRM', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Leads" ADD "TravelDates" character varying(200);

ALTER TABLE "Leads" ADD "Travelers" character varying(100);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260315231057_AddTravelDetailsToLead', '8.0.13');

COMMIT;

START TRANSACTION;

CREATE TABLE "WhatsAppBotConfigs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WelcomeMessage" character varying(1000) NOT NULL,
    "AskInterestMessage" character varying(1000) NOT NULL,
    "AskDatesMessage" character varying(1000) NOT NULL,
    "AskTravelersMessage" character varying(1000) NOT NULL,
    "ThanksMessage" character varying(1000) NOT NULL,
    "AgentRequestMessage" character varying(1000) NOT NULL,
    "DuplicateMessage" character varying(1000) NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WhatsAppBotConfigs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260315232123_AddWhatsAppBotConfig', '8.0.13');

COMMIT;

START TRANSACTION;


DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_FlightSegments_Reservations_ReservationId') THEN
        ALTER TABLE "FlightSegments" DROP CONSTRAINT "FK_FlightSegments_Reservations_ReservationId";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TravelFileAttachments_TravelFiles_TravelFileId') THEN
        ALTER TABLE "TravelFileAttachments" DROP CONSTRAINT "FK_TravelFileAttachments_TravelFiles_TravelFileId";
    END IF;
END $$;



DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK_TravelFileAttachments') THEN
        ALTER TABLE "TravelFileAttachments" DROP CONSTRAINT "PK_TravelFileAttachments";
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'TravelFileAttachments') THEN
        ALTER TABLE "TravelFileAttachments" RENAME TO "ReservaAttachments";
        ALTER INDEX IF EXISTS "IX_TravelFileAttachments_TravelFileId" RENAME TO "IX_ReservaAttachments_TravelFileId";
    END IF;
END $$;


ALTER TABLE "AfipSettings" ADD COLUMN IF NOT EXISTS "PadronSign" text;

ALTER TABLE "AfipSettings" ADD COLUMN IF NOT EXISTS "PadronToken" text;

ALTER TABLE "AfipSettings" ADD COLUMN IF NOT EXISTS "PadronTokenExpiration" timestamp with time zone;

ALTER TABLE "ReservaAttachments" ALTER COLUMN "UploadedBy" DROP NOT NULL;

ALTER TABLE "ReservaAttachments" ALTER COLUMN "ContentType" DROP NOT NULL;


DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK_ReservaAttachments') THEN
        ALTER TABLE "ReservaAttachments" ADD CONSTRAINT "PK_ReservaAttachments" PRIMARY KEY ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_FlightSegments_Reservations_ReservationId') THEN
        ALTER TABLE "FlightSegments" ADD CONSTRAINT "FK_FlightSegments_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ReservaAttachments_TravelFiles_TravelFileId') THEN
        ALTER TABLE "ReservaAttachments" ADD CONSTRAINT "FK_ReservaAttachments_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE;
    END IF;
END $$;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260319194634_ConsolidatedHotfixes', '8.0.13');

COMMIT;

START TRANSACTION;


DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'ReservaAttachments') THEN
        CREATE TABLE "ReservaAttachments" (
            "Id" SERIAL PRIMARY KEY,
            "TravelFileId" integer NOT NULL,
            "FileName" text NOT NULL,
            "StoredFileName" text NOT NULL,
            "ContentType" text,
            "FileSize" bigint NOT NULL,
            "UploadedBy" text,
            "UploadedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            CONSTRAINT "FK_ReservaAttachments_TravelFiles_TravelFileId" FOREIGN KEY ("TravelFileId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE
        );
        CREATE INDEX "IX_ReservaAttachments_TravelFileId" ON "ReservaAttachments" ("TravelFileId");
    END IF;
END $$;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260319200421_EnsureReservaAttachmentsTable', '8.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "ReservaAttachments" DROP CONSTRAINT "FK_ReservaAttachments_TravelFiles_TravelFileId";

ALTER TABLE "ReservaAttachments" RENAME COLUMN "TravelFileId" TO "ReservaId";

ALTER INDEX "IX_ReservaAttachments_TravelFileId" RENAME TO "IX_ReservaAttachments_ReservaId";

ALTER TABLE "TravelFiles" ADD "TotalPaid" numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "ReservaAttachments" ADD CONSTRAINT "FK_ReservaAttachments_TravelFiles_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260319210446_AddTotalPaidToReserva', '8.0.13');

COMMIT;

