using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TravelApi.Infrastructure.Persistence;

#nullable disable

namespace TravelApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325013000_AddBusinessSequencesAndRobustListIndexes")]
    public partial class AddBusinessSequencesAndRobustListIndexes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "BusinessSequences"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DocumentType" character varying(100) NOT NULL,
                    "Year" integer NOT NULL,
                    "LastValue" bigint NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_BusinessSequences" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_BusinessSequences_DocumentType_Year"
                ON "BusinessSequences" ("DocumentType", "Year");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Customers_IsActive_FullName"
                ON "Customers" ("IsActive", "FullName");
                """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_TravelFiles_NumeroReserva"
                ON "TravelFiles" ("FileNumber");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_TravelFiles_Status_StartDate_CreatedAt"
                ON "TravelFiles" ("Status", "StartDate", "CreatedAt");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Payments_PaidAt"
                ON "Payments" ("PaidAt");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Invoices_CreatedAt"
                ON "Invoices" ("CreatedAt");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_ManualCashMovements_OccurredAt"
                ON "ManualCashMovements" ("OccurredAt");
                """);

            var publicIdTables = new[]
            {
                "Customers",
                "FlightSegments",
                "HotelBookings",
                "Invoices",
                "LeadActivities",
                "Leads",
                "ManualCashMovements",
                "PackageBookings",
                "Passengers",
                "PaymentReceipts",
                "Payments",
                "Quotes",
                "QuoteItems",
                "Reservations",
                "ReservaAttachments",
                "Suppliers",
                "SupplierPayments",
                "TransferBookings",
                "TravelFiles"
            };

            foreach (var table in publicIdTables)
            {
                migrationBuilder.Sql($"""ALTER TABLE "{table}" ALTER COLUMN "PublicId" DROP DEFAULT;""");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP INDEX IF EXISTS "IX_ManualCashMovements_OccurredAt";""");
            migrationBuilder.Sql("""DROP INDEX IF EXISTS "IX_Invoices_CreatedAt";""");
            migrationBuilder.Sql("""DROP INDEX IF EXISTS "IX_Payments_PaidAt";""");
            migrationBuilder.Sql("""DROP INDEX IF EXISTS "IX_TravelFiles_Status_StartDate_CreatedAt";""");
            migrationBuilder.Sql("""DROP INDEX IF EXISTS "IX_TravelFiles_NumeroReserva";""");
            migrationBuilder.Sql("""DROP INDEX IF EXISTS "IX_Customers_IsActive_FullName";""");
            migrationBuilder.Sql("""DROP INDEX IF EXISTS "IX_BusinessSequences_DocumentType_Year";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "BusinessSequences";""");

            var publicIdTables = new[]
            {
                "Customers",
                "FlightSegments",
                "HotelBookings",
                "Invoices",
                "LeadActivities",
                "Leads",
                "ManualCashMovements",
                "PackageBookings",
                "Passengers",
                "PaymentReceipts",
                "Payments",
                "Quotes",
                "QuoteItems",
                "Reservations",
                "ReservaAttachments",
                "Suppliers",
                "SupplierPayments",
                "TransferBookings",
                "TravelFiles"
            };

            foreach (var table in publicIdTables)
            {
                migrationBuilder.Sql($"""ALTER TABLE "{table}" ALTER COLUMN "PublicId" SET DEFAULT gen_random_uuid();""");
            }
        }
    }
}
