using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TravelApi.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddQuotesAndCRM : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tables already exist in production (created by a previous partial migration run).
            // Using IF NOT EXISTS via raw SQL to be safe.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Leads"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""FullName"" character varying(200) NOT NULL,
                    ""Email"" character varying(200),
                    ""Phone"" character varying(50),
                    ""Status"" character varying(50) NOT NULL,
                    ""Source"" character varying(50),
                    ""InterestedIn"" character varying(200),
                    ""EstimatedBudget"" numeric(18,2) NOT NULL,
                    ""Notes"" character varying(2000),
                    ""AssignedToUserId"" text,
                    ""AssignedToName"" character varying(200),
                    ""NextFollowUp"" timestamp with time zone,
                    ""ConvertedCustomerId"" integer,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ClosedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_Leads"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Leads_Customers_ConvertedCustomerId"" FOREIGN KEY (""ConvertedCustomerId"") REFERENCES ""Customers"" (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Quotes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""QuoteNumber"" character varying(50) NOT NULL,
                    ""Title"" character varying(200) NOT NULL,
                    ""Description"" character varying(2000),
                    ""Status"" character varying(50) NOT NULL,
                    ""CustomerId"" integer,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ValidUntil"" timestamp with time zone,
                    ""AcceptedAt"" timestamp with time zone,
                    ""TravelStartDate"" timestamp with time zone,
                    ""TravelEndDate"" timestamp with time zone,
                    ""Destination"" character varying(200),
                    ""Adults"" integer NOT NULL,
                    ""Children"" integer NOT NULL,
                    ""TotalCost"" numeric(18,2) NOT NULL,
                    ""TotalSale"" numeric(18,2) NOT NULL,
                    ""GrossMargin"" numeric(18,2) NOT NULL,
                    ""ConvertedFileId"" integer,
                    ""Notes"" character varying(500),
                    CONSTRAINT ""PK_Quotes"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Quotes_Customers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""Customers"" (""Id""),
                    CONSTRAINT ""FK_Quotes_TravelFiles_ConvertedFileId"" FOREIGN KEY (""ConvertedFileId"") REFERENCES ""TravelFiles"" (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""LeadActivities"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""LeadId"" integer NOT NULL,
                    ""Type"" character varying(50) NOT NULL,
                    ""Description"" character varying(1000) NOT NULL,
                    ""CreatedBy"" character varying(200),
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_LeadActivities"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_LeadActivities_Leads_LeadId"" FOREIGN KEY (""LeadId"") REFERENCES ""Leads"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""QuoteItems"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""QuoteId"" integer NOT NULL,
                    ""ServiceType"" character varying(50) NOT NULL,
                    ""Description"" character varying(200) NOT NULL,
                    ""SupplierId"" integer,
                    ""Quantity"" integer NOT NULL,
                    ""UnitCost"" numeric(18,2) NOT NULL,
                    ""UnitPrice"" numeric(18,2) NOT NULL,
                    ""MarkupPercent"" numeric(18,2) NOT NULL,
                    ""Notes"" character varying(500),
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_QuoteItems"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_QuoteItems_Quotes_QuoteId"" FOREIGN KEY (""QuoteId"") REFERENCES ""Quotes"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_QuoteItems_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers"" (""Id"")
                );
            ");

            // Indexes - safe to recreate
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_LeadActivities_LeadId"" ON ""LeadActivities"" (""LeadId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Leads_ConvertedCustomerId"" ON ""Leads"" (""ConvertedCustomerId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_QuoteItems_QuoteId"" ON ""QuoteItems"" (""QuoteId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_QuoteItems_SupplierId"" ON ""QuoteItems"" (""SupplierId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Quotes_ConvertedFileId"" ON ""Quotes"" (""ConvertedFileId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Quotes_CustomerId"" ON ""Quotes"" (""CustomerId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "LeadActivities");
            migrationBuilder.DropTable(name: "QuoteItems");
            migrationBuilder.DropTable(name: "Leads");
            migrationBuilder.DropTable(name: "Quotes");
        }
    }
}
