using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TravelApi.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddQuotesAndCRM : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Step 1: Drop any partially-created tables from previous failed migration runs.
            // Order matters: children first, parents second.
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""LeadActivities"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""QuoteItems"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Leads"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Quotes"" CASCADE;");

            // Step 2: Create tables fresh with the correct schema.
            migrationBuilder.Sql(@"
                CREATE TABLE ""Leads"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""FullName"" character varying(200) NOT NULL,
                    ""Email"" character varying(200),
                    ""Phone"" character varying(50),
                    ""Status"" character varying(50) NOT NULL,
                    ""Source"" character varying(50),
                    ""InterestedIn"" character varying(200),
                    ""EstimatedBudget"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""Notes"" character varying(2000),
                    ""AssignedToUserId"" text,
                    ""AssignedToName"" character varying(200),
                    ""NextFollowUp"" timestamp with time zone,
                    ""ConvertedCustomerId"" integer,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ClosedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_Leads"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Leads_Customers_ConvertedCustomerId"" FOREIGN KEY (""ConvertedCustomerId"") REFERENCES ""Customers"" (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE ""Quotes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""QuoteNumber"" character varying(50) NOT NULL,
                    ""Title"" character varying(200) NOT NULL,
                    ""Description"" character varying(2000),
                    ""Status"" character varying(50) NOT NULL,
                    ""CustomerId"" integer,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ValidUntil"" timestamp with time zone,
                    ""AcceptedAt"" timestamp with time zone,
                    ""TravelStartDate"" timestamp with time zone,
                    ""TravelEndDate"" timestamp with time zone,
                    ""Destination"" character varying(200),
                    ""Adults"" integer NOT NULL DEFAULT 2,
                    ""Children"" integer NOT NULL DEFAULT 0,
                    ""TotalCost"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""TotalSale"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""GrossMargin"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""ConvertedFileId"" integer,
                    ""Notes"" character varying(500),
                    CONSTRAINT ""PK_Quotes"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Quotes_Customers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""Customers"" (""Id""),
                    CONSTRAINT ""FK_Quotes_TravelFiles_ConvertedFileId"" FOREIGN KEY (""ConvertedFileId"") REFERENCES ""Reservas"" (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE ""LeadActivities"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""LeadId"" integer NOT NULL,
                    ""Type"" character varying(50) NOT NULL,
                    ""Description"" character varying(1000) NOT NULL,
                    ""CreatedBy"" character varying(200),
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_LeadActivities"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_LeadActivities_Leads_LeadId"" FOREIGN KEY (""LeadId"") REFERENCES ""Leads"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE ""QuoteItems"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""QuoteId"" integer NOT NULL,
                    ""ServiceType"" character varying(50) NOT NULL,
                    ""Description"" character varying(200) NOT NULL,
                    ""SupplierId"" integer,
                    ""Quantity"" integer NOT NULL DEFAULT 1,
                    ""UnitCost"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""UnitPrice"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""MarkupPercent"" numeric(18,2) NOT NULL DEFAULT 0,
                    ""Notes"" character varying(500),
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_QuoteItems"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_QuoteItems_Quotes_QuoteId"" FOREIGN KEY (""QuoteId"") REFERENCES ""Quotes"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_QuoteItems_Suppliers_SupplierId"" FOREIGN KEY (""SupplierId"") REFERENCES ""Suppliers"" (""Id"")
                );
            ");

            // Step 3: Create indexes
            migrationBuilder.Sql(@"CREATE INDEX ""IX_LeadActivities_LeadId"" ON ""LeadActivities"" (""LeadId"");");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_Leads_ConvertedCustomerId"" ON ""Leads"" (""ConvertedCustomerId"");");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_QuoteItems_QuoteId"" ON ""QuoteItems"" (""QuoteId"");");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_QuoteItems_SupplierId"" ON ""QuoteItems"" (""SupplierId"");");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_Quotes_ConvertedFileId"" ON ""Quotes"" (""ConvertedFileId"");");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_Quotes_CustomerId"" ON ""Quotes"" (""CustomerId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""LeadActivities"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""QuoteItems"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Leads"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Quotes"" CASCADE;");
        }
    }
}
