using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelApi.Infrastructure.Persistence;

#nullable disable

namespace TravelApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327200000_AddRolePermissionsAndUrgentNotifications")]
    public partial class AddRolePermissionsAndUrgentNotifications : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // RolePermissions table
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "RolePermissions"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "RoleName" character varying(100) NOT NULL,
                    "Permission" character varying(100) NOT NULL,
                    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_RolePermissions_RoleName_Permission"
                ON "RolePermissions" ("RoleName", "Permission");
                """);

            // Notification enhancements
            migrationBuilder.Sql("""
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "Priority" character varying(20) NOT NULL DEFAULT 'Normal';
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "IsDismissed" boolean NOT NULL DEFAULT FALSE;
                """);

            // Seed Vendedor role if not exists
            migrationBuilder.Sql("""
                INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
                SELECT gen_random_uuid()::text, 'Vendedor', 'VENDEDOR', gen_random_uuid()::text
                WHERE NOT EXISTS (SELECT 1 FROM "AspNetRoles" WHERE "NormalizedName" = 'VENDEDOR');
                """);

            // Seed default permissions for Admin
            var adminPermissions = new[]
            {
                "reservas.view", "reservas.edit", "reservas.delete",
                "clientes.view", "clientes.edit",
                "proveedores.view", "proveedores.edit",
                "cobranzas.view", "cobranzas.edit",
                "caja.view", "caja.edit",
                "reportes.view",
                "configuracion.view", "configuracion.users", "configuracion.afip",
                "crm.view", "crm.edit",
                "tarifario.view", "tarifario.edit"
            };

            foreach (var perm in adminPermissions)
            {
                migrationBuilder.Sql($"""
                    INSERT INTO "RolePermissions" ("RoleName", "Permission")
                    SELECT 'Admin', '{perm}'
                    WHERE NOT EXISTS (SELECT 1 FROM "RolePermissions" WHERE "RoleName" = 'Admin' AND "Permission" = '{perm}');
                    """);
            }

            // Seed default permissions for Colaborador
            var colaboradorPermissions = new[]
            {
                "reservas.view", "reservas.edit",
                "clientes.view", "clientes.edit",
                "proveedores.view",
                "cobranzas.view",
                "caja.view",
                "tarifario.view"
            };

            foreach (var perm in colaboradorPermissions)
            {
                migrationBuilder.Sql($"""
                    INSERT INTO "RolePermissions" ("RoleName", "Permission")
                    SELECT 'Colaborador', '{perm}'
                    WHERE NOT EXISTS (SELECT 1 FROM "RolePermissions" WHERE "RoleName" = 'Colaborador' AND "Permission" = '{perm}');
                    """);
            }

            // Seed default permissions for Vendedor
            var vendedorPermissions = new[]
            {
                "reservas.view", "reservas.edit",
                "clientes.view", "clientes.edit",
                "crm.view", "crm.edit",
                "cobranzas.view",
                "tarifario.view"
            };

            foreach (var perm in vendedorPermissions)
            {
                migrationBuilder.Sql($"""
                    INSERT INTO "RolePermissions" ("RoleName", "Permission")
                    SELECT 'Vendedor', '{perm}'
                    WHERE NOT EXISTS (SELECT 1 FROM "RolePermissions" WHERE "RoleName" = 'Vendedor' AND "Permission" = '{perm}');
                    """);
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "RolePermissions";""");
            migrationBuilder.Sql("""ALTER TABLE "Notifications" DROP COLUMN IF EXISTS "Priority";""");
            migrationBuilder.Sql("""ALTER TABLE "Notifications" DROP COLUMN IF EXISTS "IsDismissed";""");
        }
    }
}
