using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TravelApi.Infrastructure.Persistence.Migrations.App
{
    [Migration("20260427000000_AddVouchersAndMessages")]
    public partial class AddVouchersAndMessages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Vouchers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PublicId" uuid NOT NULL DEFAULT gen_random_uuid(),
                    "ReservaId" integer NOT NULL,
                    "Source" character varying(30) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "Scope" character varying(40) NOT NULL,
                    "FileName" character varying(255) NOT NULL,
                    "StoredFileName" character varying(500) NULL,
                    "ContentType" character varying(120) NOT NULL,
                    "FileSize" bigint NOT NULL,
                    "ExternalOrigin" character varying(200) NULL,
                    "IsEnabledForSending" boolean NOT NULL,
                    "CreatedByUserId" character varying(200) NULL,
                    "CreatedByUserName" character varying(200) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "IssuedByUserId" character varying(200) NULL,
                    "IssuedByUserName" character varying(200) NULL,
                    "IssuedAt" timestamp with time zone NULL,
                    "IssueReason" character varying(1000) NULL,
                    "WasExceptionalIssue" boolean NOT NULL DEFAULT FALSE,
                    "ExceptionalReason" character varying(1000) NULL,
                    "AuthorizedBySuperiorUserId" character varying(200) NULL,
                    "AuthorizedBySuperiorUserName" character varying(200) NULL,
                    "OutstandingBalanceAtIssue" numeric(18,2) NOT NULL DEFAULT 0,
                    CONSTRAINT "PK_Vouchers" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Vouchers_TravelFiles_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Vouchers_PublicId" ON "Vouchers" ("PublicId");
                CREATE INDEX IF NOT EXISTS "IX_Vouchers_ReservaId_Status" ON "Vouchers" ("ReservaId", "Status");

                CREATE TABLE IF NOT EXISTS "VoucherPassengerAssignments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "VoucherId" integer NOT NULL,
                    "PassengerId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_VoucherPassengerAssignments" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_VoucherPassengerAssignments_Vouchers_VoucherId" FOREIGN KEY ("VoucherId") REFERENCES "Vouchers" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VoucherPassengerAssignments_Passengers_PassengerId" FOREIGN KEY ("PassengerId") REFERENCES "Passengers" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_VoucherPassengerAssignments_VoucherId_PassengerId"
                    ON "VoucherPassengerAssignments" ("VoucherId", "PassengerId");
                CREATE INDEX IF NOT EXISTS "IX_VoucherPassengerAssignments_PassengerId"
                    ON "VoucherPassengerAssignments" ("PassengerId");

                CREATE TABLE IF NOT EXISTS "VoucherAuditEntries" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "VoucherId" integer NOT NULL,
                    "ReservaId" integer NOT NULL,
                    "Action" character varying(50) NOT NULL,
                    "UserId" character varying(200) NOT NULL,
                    "UserName" character varying(200) NULL,
                    "OccurredAt" timestamp with time zone NOT NULL,
                    "Reason" character varying(1000) NULL,
                    "ReservationHadOutstandingBalance" boolean NOT NULL,
                    "OutstandingBalance" numeric(18,2) NOT NULL,
                    "AuthorizedBySuperiorUserId" character varying(200) NULL,
                    "AuthorizedBySuperiorUserName" character varying(200) NULL,
                    "Details" character varying(2000) NULL,
                    CONSTRAINT "PK_VoucherAuditEntries" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_VoucherAuditEntries_Vouchers_VoucherId" FOREIGN KEY ("VoucherId") REFERENCES "Vouchers" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_VoucherAuditEntries_TravelFiles_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "TravelFiles" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_VoucherAuditEntries_VoucherId" ON "VoucherAuditEntries" ("VoucherId");
                CREATE INDEX IF NOT EXISTS "IX_VoucherAuditEntries_ReservaId_OccurredAt" ON "VoucherAuditEntries" ("ReservaId", "OccurredAt");

                CREATE TABLE IF NOT EXISTS "MessageDeliveries" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PublicId" uuid NOT NULL DEFAULT gen_random_uuid(),
                    "ReservaId" integer NULL,
                    "PassengerId" integer NULL,
                    "CustomerId" integer NULL,
                    "VoucherId" integer NULL,
                    "Channel" character varying(30) NOT NULL,
                    "Kind" character varying(30) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "Phone" character varying(50) NOT NULL,
                    "MessageText" character varying(2000) NULL,
                    "AttachmentName" character varying(255) NULL,
                    "BotMessageId" character varying(200) NULL,
                    "SentByUserId" character varying(200) NULL,
                    "SentByUserName" character varying(200) NULL,
                    "Error" character varying(1000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "SentAt" timestamp with time zone NULL,
                    CONSTRAINT "PK_MessageDeliveries" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_MessageDeliveries_TravelFiles_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "TravelFiles" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_MessageDeliveries_Passengers_PassengerId" FOREIGN KEY ("PassengerId") REFERENCES "Passengers" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_MessageDeliveries_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_MessageDeliveries_Vouchers_VoucherId" FOREIGN KEY ("VoucherId") REFERENCES "Vouchers" ("Id") ON DELETE SET NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_MessageDeliveries_PublicId" ON "MessageDeliveries" ("PublicId");
                CREATE INDEX IF NOT EXISTS "IX_MessageDeliveries_ReservaId_CreatedAt" ON "MessageDeliveries" ("ReservaId", "CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_MessageDeliveries_VoucherId" ON "MessageDeliveries" ("VoucherId");
            """);

            var permissions = new[]
            {
                "vouchers.generate",
                "vouchers.issue",
                "vouchers.upload",
                "vouchers.send",
                "vouchers.authorize_exception",
                "messages.view",
                "messages.send"
            };

            foreach (var permission in permissions)
            {
                migrationBuilder.Sql($"""
                    INSERT INTO "RolePermissions" ("RoleName", "Permission")
                    SELECT 'Admin', '{permission}'
                    WHERE NOT EXISTS (
                        SELECT 1 FROM "RolePermissions"
                        WHERE "RoleName" = 'Admin' AND "Permission" = '{permission}'
                    );
                """);
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "MessageDeliveries";
                DROP TABLE IF EXISTS "VoucherAuditEntries";
                DROP TABLE IF EXISTS "VoucherPassengerAssignments";
                DROP TABLE IF EXISTS "Vouchers";
            """);
        }
    }
}
