using Microsoft.EntityFrameworkCore;

namespace TravelApi.Infrastructure.Persistence;

public static class OperationalFinanceSchemaBootstrapper
{
    public const string OperationalFinanceMigrationId = "20260322010000_AddOperationalFinanceAndTreasury";
    private const string EfProductVersion = "8.0.13";

    private static readonly string[] Statements =
    {
        @"ALTER TABLE ""TravelFiles"" ADD COLUMN IF NOT EXISTS ""TotalPaid"" numeric(18,2) NOT NULL DEFAULT 0.0;",
        @"ALTER TABLE ""TravelFiles"" ADD COLUMN IF NOT EXISTS ""ResponsibleUserId"" text;",

        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""AffectsCash"" boolean NOT NULL DEFAULT TRUE;",
        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""EntryType"" character varying(50) NOT NULL DEFAULT 'Payment';",
        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""OriginalPaymentId"" integer;",
        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""RelatedInvoiceId"" integer;",

        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""WasForced"" boolean NOT NULL DEFAULT FALSE;",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForceReason"" character varying(1000);",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForcedByUserId"" character varying(200);",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForcedByUserName"" character varying(200);",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForcedAt"" timestamp with time zone;",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""OutstandingBalanceAtIssuance"" numeric(18,2) NOT NULL DEFAULT 0.0;",

        @"CREATE TABLE IF NOT EXISTS ""OperationalFinanceSettings"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""RequireFullPaymentForOperativeStatus"" boolean NOT NULL DEFAULT TRUE,
            ""RequireFullPaymentForVoucher"" boolean NOT NULL DEFAULT TRUE,
            ""AfipInvoiceControlMode"" character varying(50) NOT NULL DEFAULT 'AllowAgentOverrideWithReason',
            ""EnableUpcomingUnpaidReservationNotifications"" boolean NOT NULL DEFAULT TRUE,
            ""UpcomingUnpaidReservationAlertDays"" integer NOT NULL DEFAULT 7,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
            ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT NOW()
        );",
        @"INSERT INTO ""OperationalFinanceSettings""
            (""RequireFullPaymentForOperativeStatus"", ""RequireFullPaymentForVoucher"", ""AfipInvoiceControlMode"", ""EnableUpcomingUnpaidReservationNotifications"", ""UpcomingUnpaidReservationAlertDays"", ""CreatedAt"", ""UpdatedAt"")
          SELECT TRUE, TRUE, 'AllowAgentOverrideWithReason', TRUE, 7, NOW(), NOW()
          WHERE NOT EXISTS (SELECT 1 FROM ""OperationalFinanceSettings"");",

        @"CREATE TABLE IF NOT EXISTS ""PaymentReceipts"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""PaymentId"" integer NOT NULL,
            ""ReservaId"" integer NOT NULL,
            ""ReceiptNumber"" character varying(50) NOT NULL,
            ""IssuedAt"" timestamp with time zone NOT NULL,
            ""Amount"" numeric(18,2) NOT NULL,
            ""Status"" character varying(30) NOT NULL,
            ""VoidedAt"" timestamp with time zone NULL
        );",
        @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PaymentReceipts_PaymentId"" ON ""PaymentReceipts"" (""PaymentId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_PaymentReceipts_ReservaId"" ON ""PaymentReceipts"" (""ReservaId"");",

        @"CREATE TABLE IF NOT EXISTS ""ManualCashMovements"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""Direction"" character varying(20) NOT NULL,
            ""Amount"" numeric(18,2) NOT NULL,
            ""OccurredAt"" timestamp with time zone NOT NULL,
            ""Method"" character varying(50) NOT NULL,
            ""Category"" character varying(100) NOT NULL,
            ""Description"" character varying(500) NOT NULL,
            ""Reference"" character varying(100) NULL,
            ""CreatedBy"" character varying(200) NOT NULL,
            ""IsVoided"" boolean NOT NULL DEFAULT FALSE,
            ""VoidedAt"" timestamp with time zone NULL,
            ""RelatedReservaId"" integer NULL,
            ""RelatedSupplierId"" integer NULL
        );",
        @"CREATE INDEX IF NOT EXISTS ""IX_ManualCashMovements_RelatedReservaId"" ON ""ManualCashMovements"" (""RelatedReservaId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_ManualCashMovements_RelatedSupplierId"" ON ""ManualCashMovements"" (""RelatedSupplierId"");",

        @"CREATE INDEX IF NOT EXISTS ""IX_TravelFiles_ResponsibleUserId"" ON ""TravelFiles"" (""ResponsibleUserId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_Payments_OriginalPaymentId"" ON ""Payments"" (""OriginalPaymentId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_Payments_RelatedInvoiceId"" ON ""Payments"" (""RelatedInvoiceId"");",

        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ManualCashMovements_Suppliers_RelatedSupplierId') THEN
                ALTER TABLE ""ManualCashMovements""
                    ADD CONSTRAINT ""FK_ManualCashMovements_Suppliers_RelatedSupplierId""
                    FOREIGN KEY (""RelatedSupplierId"") REFERENCES ""Suppliers"" (""Id"") ON DELETE SET NULL;
            END IF;
        END
        $$;",
        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ManualCashMovements_TravelFiles_RelatedReservaId') THEN
                ALTER TABLE ""ManualCashMovements""
                    ADD CONSTRAINT ""FK_ManualCashMovements_TravelFiles_RelatedReservaId""
                    FOREIGN KEY (""RelatedReservaId"") REFERENCES ""TravelFiles"" (""Id"") ON DELETE SET NULL;
            END IF;
        END
        $$;",
        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PaymentReceipts_Payments_PaymentId') THEN
                ALTER TABLE ""PaymentReceipts""
                    ADD CONSTRAINT ""FK_PaymentReceipts_Payments_PaymentId""
                    FOREIGN KEY (""PaymentId"") REFERENCES ""Payments"" (""Id"") ON DELETE RESTRICT;
            END IF;
        END
        $$;",
        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PaymentReceipts_TravelFiles_ReservaId') THEN
                ALTER TABLE ""PaymentReceipts""
                    ADD CONSTRAINT ""FK_PaymentReceipts_TravelFiles_ReservaId""
                    FOREIGN KEY (""ReservaId"") REFERENCES ""TravelFiles"" (""Id"") ON DELETE RESTRICT;
            END IF;
        END
        $$;",
        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Payments_Invoices_RelatedInvoiceId') THEN
                ALTER TABLE ""Payments""
                    ADD CONSTRAINT ""FK_Payments_Invoices_RelatedInvoiceId""
                    FOREIGN KEY (""RelatedInvoiceId"") REFERENCES ""Invoices"" (""Id"") ON DELETE SET NULL;
            END IF;
        END
        $$;",
        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Payments_Payments_OriginalPaymentId') THEN
                ALTER TABLE ""Payments""
                    ADD CONSTRAINT ""FK_Payments_Payments_OriginalPaymentId""
                    FOREIGN KEY (""OriginalPaymentId"") REFERENCES ""Payments"" (""Id"") ON DELETE SET NULL;
            END IF;
        END
        $$;",
        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_TravelFiles_AspNetUsers_ResponsibleUserId') THEN
                ALTER TABLE ""TravelFiles""
                    ADD CONSTRAINT ""FK_TravelFiles_AspNetUsers_ResponsibleUserId""
                    FOREIGN KEY (""ResponsibleUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL;
            END IF;
        END
        $$;"
    };

    public static async Task EnsureAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        foreach (var statement in Statements)
        {
            await dbContext.Database.ExecuteSqlRawAsync(statement, cancellationToken);
        }
    }

    public static async Task MarkOperationalFinanceMigrationAsAppliedAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        var sql = $"""
            CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                "MigrationId" character varying(150) NOT NULL,
                "ProductVersion" character varying(32) NOT NULL,
                CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
            );

            INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
            SELECT '{OperationalFinanceMigrationId}', '{EfProductVersion}'
            WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'OperationalFinanceSettings')
              AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'PaymentReceipts')
              AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ManualCashMovements')
              AND NOT EXISTS (
                    SELECT 1
                    FROM "__EFMigrationsHistory"
                    WHERE "MigrationId" = '{OperationalFinanceMigrationId}'
              );
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }
}
