using Microsoft.EntityFrameworkCore;

namespace TravelApi.Infrastructure.Persistence;

public static class OperationalFinanceSchemaBootstrapper
{
    private static readonly string[] Statements =
    {
        @"ALTER TABLE ""TravelFiles"" ADD COLUMN IF NOT EXISTS ""TotalPaid"" numeric(18,2) NOT NULL DEFAULT 0.0;",
        @"ALTER TABLE ""TravelFiles"" ADD COLUMN IF NOT EXISTS ""ResponsibleUserId"" text;",

        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""AffectsCash"" boolean NOT NULL DEFAULT TRUE;",
        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""EntryType"" character varying(50) NOT NULL DEFAULT 'Payment';",
        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""OriginalPaymentId"" integer;",
        @"ALTER TABLE ""Payments"" ADD COLUMN IF NOT EXISTS ""RelatedInvoiceId"" integer;",

        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""WasForced"" boolean NOT NULL DEFAULT FALSE;",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForceReason"" character varying(1000);",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForcedByUserId"" character varying(200);",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForcedByUserName"" character varying(200);",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""ForcedAt"" timestamp with time zone;",
        @"ALTER TABLE ""Invoices"" ADD COLUMN IF NOT EXISTS ""OutstandingBalanceAtIssuance"" numeric(18,2) NOT NULL DEFAULT 0.0;",

        @"CREATE TABLE IF NOT EXISTS ""OperationalFinanceSettings"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""RequireFullPaymentForOperativeStatus"" boolean NOT NULL DEFAULT TRUE,
            ""RequireFullPaymentForVoucher"" boolean NOT NULL DEFAULT TRUE,
            ""AfipInvoiceControlMode"" character varying(50) NOT NULL DEFAULT 'AllowAgentOverrideWithReason',
            ""EnableUpcomingUnpaidReservationNotifications"" boolean NOT NULL DEFAULT TRUE,
            ""UpcomingUnpaidReservationAlertDays"" integer NOT NULL DEFAULT 7,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
            ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT NOW()
        );",
        @"INSERT INTO ""OperationalFinanceSettings""
            (""RequireFullPaymentForOperativeStatus"", ""RequireFullPaymentForVoucher"", ""AfipInvoiceControlMode"", ""EnableUpcomingUnpaidReservationNotifications"", ""UpcomingUnpaidReservationAlertDays"", ""CreatedAt"", ""UpdatedAt"")
          SELECT TRUE, TRUE, 'AllowAgentOverrideWithReason', TRUE, 7, NOW(), NOW()
          WHERE NOT EXISTS (SELECT 1 FROM ""OperationalFinanceSettings"");",

        @"CREATE TABLE IF NOT EXISTS ""PaymentReceipts"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""PaymentId"" integer NOT NULL,
            ""ReservaId"" integer NOT NULL,
            ""ReceiptNumber"" character varying(50) NOT NULL,
            ""IssuedAt"" timestamp with time zone NOT NULL,
            ""Amount"" numeric(18,2) NOT NULL,
            ""Status"" character varying(30) NOT NULL,
            ""VoidedAt"" timestamp with time zone NULL
        );",
        @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PaymentReceipts_PaymentId"" ON ""PaymentReceipts"" (""PaymentId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_PaymentReceipts_ReservaId"" ON ""PaymentReceipts"" (""ReservaId"");",

        @"CREATE TABLE IF NOT EXISTS ""ManualCashMovements"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""Direction"" character varying(20) NOT NULL,
            ""Amount"" numeric(18,2) NOT NULL,
            ""OccurredAt"" timestamp with time zone NOT NULL,
            ""Method"" character varying(50) NOT NULL,
            ""Category"" character varying(100) NOT NULL,
            ""Description"" character varying(500) NOT NULL,
            ""Reference"" character varying(100) NULL,
            ""CreatedBy"" character varying(200) NOT NULL,
            ""IsVoided"" boolean NOT NULL DEFAULT FALSE,
            ""VoidedAt"" timestamp with time zone NULL,
            ""RelatedReservaId"" integer NULL,
            ""RelatedSupplierId"" integer NULL
        );",
        @"CREATE INDEX IF NOT EXISTS ""IX_ManualCashMovements_RelatedReservaId"" ON ""ManualCashMovements"" (""RelatedReservaId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_ManualCashMovements_RelatedSupplierId"" ON ""ManualCashMovements"" (""RelatedSupplierId"");",

        @"CREATE INDEX IF NOT EXISTS ""IX_TravelFiles_ResponsibleUserId"" ON ""TravelFiles"" (""ResponsibleUserId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_Payments_OriginalPaymentId"" ON ""Payments"" (""OriginalPaymentId"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_Payments_RelatedInvoiceId"" ON ""Payments"" (""RelatedInvoiceId"");"
    };

    public static async Task EnsureAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        foreach (var statement in Statements)
        {
            await dbContext.Database.ExecuteSqlRawAsync(statement, cancellationToken);
        }
    }
}
