using Microsoft.EntityFrameworkCore;

namespace TravelApi.Infrastructure.Persistence;

public static class RefreshTokenSchemaBootstrapper
{
    public const string RefreshTokenMigrationId = "20260325003000_AddRefreshTokens";
    private const string EfProductVersion = "8.0.13";

    private static readonly string[] Statements =
    {
        @"CREATE TABLE IF NOT EXISTS ""RefreshTokens"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""TokenHash"" character varying(256) NOT NULL,
            ""UserId"" character varying(450) NOT NULL,
            ""CreatedByIp"" character varying(64),
            ""UserAgent"" character varying(512),
            ""IsPersistent"" boolean NOT NULL DEFAULT FALSE,
            ""CreatedAt"" timestamp with time zone NOT NULL,
            ""ExpiresAt"" timestamp with time zone NOT NULL,
            ""RevokedAt"" timestamp with time zone NULL,
            ""ReplacedByTokenHash"" character varying(256) NULL
        );",
        @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_RefreshTokens_TokenHash"" ON ""RefreshTokens"" (""TokenHash"");",
        @"CREATE INDEX IF NOT EXISTS ""IX_RefreshTokens_UserId_ExpiresAt"" ON ""RefreshTokens"" (""UserId"", ""ExpiresAt"");",
        @"DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_RefreshTokens_AspNetUsers_UserId') THEN
                ALTER TABLE ""RefreshTokens""
                    ADD CONSTRAINT ""FK_RefreshTokens_AspNetUsers_UserId""
                    FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE;
            END IF;
        END
        $$;"
    };

    public static async Task EnsureAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        foreach (var statement in Statements)
        {
            await dbContext.Database.ExecuteSqlRawAsync(statement, cancellationToken);
        }
    }

    public static async Task MarkRefreshTokenMigrationAsAppliedAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        var sql = $"""
            CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                "MigrationId" character varying(150) NOT NULL,
                "ProductVersion" character varying(32) NOT NULL,
                CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
            );

            INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
            SELECT '{RefreshTokenMigrationId}', '{EfProductVersion}'
            WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'RefreshTokens')
              AND NOT EXISTS (
                    SELECT 1
                    FROM "__EFMigrationsHistory"
                    WHERE "MigrationId" = '{RefreshTokenMigrationId}'
              );
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }
}
