START TRANSACTION;

-- 1. Safely add OriginalInvoiceId column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Invoices' AND column_name = 'OriginalInvoiceId') THEN
        ALTER TABLE "Invoices" ADD "OriginalInvoiceId" integer;
    END IF;
END $$;

-- 2. Create InvoiceItems table if not exists
CREATE TABLE IF NOT EXISTS "InvoiceItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" integer NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "AlicuotaIvaId" integer NOT NULL,
    "ImporteIva" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_InvoiceItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceItems_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);

-- 3. Create InvoiceTributes table if not exists
CREATE TABLE IF NOT EXISTS "InvoiceTributes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" integer NOT NULL,
    "TributeId" integer NOT NULL,
    "Description" character varying(200) NOT NULL,
    "BaseImponible" numeric(18,2) NOT NULL,
    "Alicuota" numeric(18,2) NOT NULL,
    "Importe" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_InvoiceTributes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceTributes_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);

-- 4. Safely create indexes
CREATE INDEX IF NOT EXISTS "IX_Invoices_OriginalInvoiceId" ON "Invoices" ("OriginalInvoiceId");
CREATE INDEX IF NOT EXISTS "IX_InvoiceItems_InvoiceId" ON "InvoiceItems" ("InvoiceId");
CREATE INDEX IF NOT EXISTS "IX_InvoiceTributes_InvoiceId" ON "InvoiceTributes" ("InvoiceId");

-- 5. Safely add foreign key constraint for OriginalInvoiceId
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_Invoices_Invoices_OriginalInvoiceId') THEN
        ALTER TABLE "Invoices" ADD CONSTRAINT "FK_Invoices_Invoices_OriginalInvoiceId" FOREIGN KEY ("OriginalInvoiceId") REFERENCES "Invoices" ("Id");
    END IF;
END $$;

-- 6. Insert migration history if not exists
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260216195937_AddAccountingEntities', '8.0.8'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216195937_AddAccountingEntities');

COMMIT;
