START TRANSACTION;

ALTER TABLE "Invoices" ADD "OriginalInvoiceId" integer;

CREATE TABLE "InvoiceItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" integer NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "AlicuotaIvaId" integer NOT NULL,
    "ImporteIva" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_InvoiceItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceItems_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InvoiceTributes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" integer NOT NULL,
    "TributeId" integer NOT NULL,
    "Description" character varying(200) NOT NULL,
    "BaseImponible" numeric(18,2) NOT NULL,
    "Alicuota" numeric(18,2) NOT NULL,
    "Importe" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_InvoiceTributes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceTributes_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Invoices_OriginalInvoiceId" ON "Invoices" ("OriginalInvoiceId");

CREATE INDEX "IX_InvoiceItems_InvoiceId" ON "InvoiceItems" ("InvoiceId");

CREATE INDEX "IX_InvoiceTributes_InvoiceId" ON "InvoiceTributes" ("InvoiceId");

ALTER TABLE "Invoices" ADD CONSTRAINT "FK_Invoices_Invoices_OriginalInvoiceId" FOREIGN KEY ("OriginalInvoiceId") REFERENCES "Invoices" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216195937_AddAccountingEntities', '8.0.8');

COMMIT;

